name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - dev
      - release

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOORECOIN_65280 }}
          projectId: moorecoin-65280
          channelId: ${{ github.ref == 'refs/heads/dev' && 'dev' || 'live' }}
